name: Build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MAPI
        run: |
            Invoke-WebRequest -Uri "https://files.catbox.moe/ut01ee.zip" -OutFile API.zip
            Expand-Archive -Path API.zip -DestinationPath API

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Prepare artifacts for release
        uses: actions/upload-artifact@v2
        with:
          name: Publish
          path: MagicUI/bin/Publish
  release:
    needs:
      - build
    runs-on: windows-latest
    # only make a release if we manually request the build - other builds will be handled automatically with a push
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            artifacts/MagicUI.zip