name: Build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MAPI
        run: |
            wget https://files.catbox.moe/felhio.zip -O API.zip
            unzip API.zip -d API

      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - name: Setup ms-build
        run: sudo apt-get install -y nuget mono-devel mono-xbuild
      
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release