name: Build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MAPI
        run: |
            Invoke-WebRequest -Uri "https://files.catbox.moe/ut01ee.zip" -OutFile API.zip
            Expand-Archive -Path API.zip -DestinationPath API

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release