name: Docs

on:
  push:
    branches: [ master ]

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup MAPI
        uses: BadMagic100/setup-hk@v2
        with:
          apiPath: HKManaged
        
      # setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      
      - name: Install dependencies
        run: dotnet restore
        
      # required for our janky local source generator setup
      - name: Codegen
        run: dotnet build -c Release
        
      # Install DocFX
      - name: Setup DocFX
        run: dotnet tool update -g docfx
      
      # Build and publish docs
      - name: DocFX build
        working-directory: docs
        run: docfx docfx.json
        continue-on-error: false

      - name: Upload assets
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
