name: Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-docs:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MAPI
        run: |
            wget https://files.catbox.moe/ut01ee.zip -O API.zip
            unzip API.zip -d API
        
      # setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - name: Setup ms-build
        run: sudo apt-get install -y nuget mono-devel mono-xbuild
      
      - name: Install dependencies
        run: dotnet restore
        
      # Install DocFX
      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx
      
      # Build and publish docs
      - name: DocFX build
        working-directory: MagicUI/docs
        run: docfx docfx.json
        continue-on-error: false

      - name: Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: MagicUI/docs/_site
          force_orphan: true