name: Docs

on:
  push:
    branches: [ master, docs-source ]

jobs:
  generate-docs:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout doc source
        uses: actions/checkout@v2
        with:
          ref: docs-source
          path: docs
        
      # setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      
      - name: Install dependencies
        run: dotnet restore
        
      # Install DocFX
      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install docfx
      
      # Build and publish docs
      - name: DocFX build
        working-directory: docs
        run: docfx docfx.json
        continue-on-error: false

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          force_orphan: true
